/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.68
 * Generated at: 2016-04-22 08:47:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class ShowLocation_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=windows-1256");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\"\n");
      out.write("\tcontent=\"text/html; charset=windows-1256\">\n");
      out.write("<title>FCISquare Application</title>\n");
      out.write("<script src=\"http://maps.googleapis.com/maps/api/js\">\n");
      out.write("\t\n");
      out.write("</script>\n");
      out.write("<script>\n");
      out.write("\tfunction getLocation() {\n");
      out.write("\t\tif (navigator.geolocation) {\n");
      out.write("\t\t\tnavigator.geolocation.getCurrentPosition(showPosition, showError);\n");
      out.write("\t\t} else {\n");
      out.write("\n");
      out.write("\t\t}\n");
      out.write("\t}\n");
      out.write("\n");
      out.write("\tfunction showPosition(position) {\n");
      out.write("\t\tdocument.getElementById('lat').value = position.coords.latitude;\n");
      out.write("\t\tdocument.getElementById('long').value = position.coords.longitude;\n");
      out.write("\t\tvar myLatLng = {\n");
      out.write("\t\t\tlat : position.coords.latitude,\n");
      out.write("\t\t\tlng : position.coords.longitude\n");
      out.write("\t\t};\n");
      out.write("\t\tvar map = {\n");
      out.write("\t\t\tcenter : myLatLng,\n");
      out.write("\t\t\tzoom : 15,\n");
      out.write("\t\t\tmapTypeId : google.maps.MapTypeId.ROADMAP\n");
      out.write("\t\t};\n");
      out.write("\t\tvar map = new google.maps.Map(document.getElementById(\"googleMap\"), map);\n");
      out.write("\t\tvar marker = new google.maps.Marker({\n");
      out.write("\t\t\tposition : myLatLng,\n");
      out.write("\t\t\tmap : map,\n");
      out.write("\t\t\ttitle : 'You are here, ta2reban ensh2allah ya3ny :D :D '\n");
      out.write("\t\t});\n");
      out.write("\n");
      out.write("\t}\n");
      out.write("\n");
      out.write("\tfunction showError(error) {\n");
      out.write("\t\tswitch (error.code) {\n");
      out.write("\t\tcase error.PERMISSION_DENIED:\n");
      out.write("\t\t\tx.innerHTML = \"User denied the request for Geolocation.\"\n");
      out.write("\t\t\tbreak;\n");
      out.write("\t\tcase error.POSITION_UNAVAILABLE:\n");
      out.write("\t\t\tx.innerHTML = \"Location information is unavailable.\"\n");
      out.write("\t\t\tbreak;\n");
      out.write("\t\tcase error.TIMEOUT:\n");
      out.write("\t\t\tx.innerHTML = \"The request to get user location timed out.\"\n");
      out.write("\t\t\tbreak;\n");
      out.write("\t\tcase error.UNKNOWN_ERROR:\n");
      out.write("\t\t\tx.innerHTML = \"An unknown error occurred.\"\n");
      out.write("\t\t\tbreak;\n");
      out.write("\t\t}\n");
      out.write("\t}\n");
      out.write("\tgoogle.maps.event.addDomListener(window, 'load', getLocation);\n");
      out.write("</script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\t<div id=\"googleMap\" style=\"width: 500px; height: 380px;\"></div>\n");
      out.write("\t<br>\n");
      out.write("\t<form action=\"updateMyLocation\" method=\"post\">\n");
      out.write("\n");
      out.write("\t\t<input id=\"lat\" type=\"hidden\" name=\"lat\" /> <input id=\"long\"\n");
      out.write("\t\t\ttype=\"hidden\" name=\"long\" /> <input type=\"submit\"\n");
      out.write("\t\t\tvalue=\"update my current position\" />\n");
      out.write("\t</form>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
